(defun append-string-to-eol ()
  "Add string at the end of the line and return to current position"
  (interactive)
  (setq current (point))
  (end-of-line)
  (if (not (= (preceding-char) 59))
    (insert ";")
    (delete-backward-char 1))
  (goto-char current)
  )
