(defun move-line-down ()
  (interactive)
  (let ((col (current-column)))
    (forward-line)
    (transpose-lines 1)
    (previous-line)
    (move-to-column col)))

(defun move-line-up ()
  (interactive)
  (let ((col (current-column)))
    (transpose-lines 1)
    (previous-line 2)
    (move-to-column col)))
