(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(font-lock-comment-face ((t (:foreground "#969896"))))
 '(font-lock-function-name-face ((t (:foreground "#7F33A9"))))
 '(font-lock-keyword-face ((t (:foreground "#9D1353"))))
 '(font-lock-string-face ((t (:foreground "#15309F"))))
 '(font-lock-type-face ((t (:foreground "#0086b3"))))
 '(font-lock-variable-name-face ((t (:foreground "gold4"))))
 '(helm-buffer-directory ((t (:inherit helm-ff-directory))))
 '(helm-buffer-file ((t (:foreground "black"))))
 '(helm-buffer-process ((t (:foreground "light slate gray"))))
 '(helm-ff-directory ((t (:background "gainsboro" :foreground "#4b2500"))))
 '(helm-ff-dotted-directory ((t (:inherit helm-ff-directory :foreground "gray"))))
 '(helm-ff-file ((t (:inherit font-lock-builtin-face :foreground "black"))))
 '(helm-source-header ((t (:background "dark gray" :foreground "gray10" :box (:line-width 5 :color "grey75") :weight bold :height 1.3 :family "Sans Serif"))))
 '(markdown-header-face-1 ((t (:inherit outline-1 :background "#EFDFFF" :foreground "#408" :weight bold :height 1.6))))
 '(markdown-header-face-2 ((t (:inherit outline-2 :background "#FFDFEF" :foreground "#804" :weight bold :height 1.4))))
 '(markdown-header-face-3 ((t (:inherit outline-3 :background "#FFEFDF" :foreground "#840" :weight bold :height 1.3))))
 '(markdown-header-face-4 ((t (:inherit outline-4 :background "#DFEFFF" :foreground "#048" :weight bold :height 1.15))))
 '(markdown-header-face-5 ((t (:inherit outline-5 :background "#EFDFFF" :foreground "#306" :weight bold :height 1.0))))
 '(markdown-header-face-6 ((t (:inherit outline-6 :background "#FFDFEF" :foreground "#603" :weight bold :height 1.0))))
 '(markdown-header-face-7 ((t (:inherit outline-7 :background "#FFEFDF" :foreground "#630" :weight bold :height 1.0))))
 '(markdown-header-face-8 ((t (:inherit outline-8 :background "#DFEFFF" :foreground "#036" :weight bold :height 1.0))))
 '(minimap-active-region-background ((((background dark)) (:background "#2A2A2A222222")) (t (:background "#D3D3D3222222"))) nil :group)
 '(mode-line ((t (:background "grey75" :foreground "#555" :box (:line-width -1 :style released-button)))))
 '(my-unexistent-face ((t (:foreground "#000000"))))
 '(org-level-1 ((t (:inherit outline-1 :foreground "#00F" :weight bold :height 1.5))))
 '(org-level-2 ((t (:inherit outline-2 :foreground "#0AF" :weight bold :height 1.3))))
 '(org-level-3 ((t (:inherit outline-3 :foreground "#0FA" :weight bold :height 1.15))))
 '(org-level-4 ((t (:inherit outline-4 :foreground "#9E0" :weight bold :height 1.0))))
 '(org-level-5 ((t (:inherit outline-5 :foreground "#CC0" :weight bold :height 1.0))))
 '(org-level-6 ((t (:inherit outline-6 :foreground "#EA0" :weight bold :height 1.0))))
 '(org-level-7 ((t (:inherit outline-7 :foreground "#D60" :weight bold :height 1.0))))
 '(org-level-8 ((t (:inherit outline-8 :foreground "#90E" :weight bold :height 1.0))))
 '(region ((t (:background "gold" :distant-foreground "white"))))
 '(show-paren-mismatch ((t (:background "#E04151" :foreground "white"))))
 '(tabbar-button ((t (:inherit tabbar-default :weight normal))))
 '(tabbar-button-highlight ((t (:inherit tabbar-default))))
 '(tabbar-default ((t (:inherit default :background "#3d3c3a" :foreground "#999" :weight medium :overline nil :underline nil :height 0.9 :widthtype semi-condensed))))
 '(tabbar-highlight ((t (:inherit tabbar-default :background "#FA9"))))
 '(tabbar-modified ((t (:inherit tabbar-default))))
 '(tabbar-selected ((t (:inherit tabbar-default :background "#BBBBBF" :foreground "#333"))))
 '(tabbar-selected-modified ((t (:inherit tabbar-selected))))
 '(tabbar-separator ((t (:inherit tabbar-default :background "#333"))))
 '(tabbar-unselected ((t (:inherit tabbar-default)))))
