;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        acg-backward-kill-sexp
        acg-calc-eval
        acg-clipboard-paste-replace-selection
        acg-forward-kill-sexp
        acg-kill-line-or-region
        acg-kill-line-or-region-backwards
        acg-kill-sexp
        acg-move-beginning-of-line
        acg-windows-clipboard-paste-replace-selection
        clipboard-kill-region
        clipboard-kill-ring-save
        clipboard-paste-replace-selection
        crux-kill-line-backwards
        crux-smart-open-line-above
        helm-mini
        indent-for-tab-command
        keyboard-escape-quit
        keyboard-quit
        kill-line-or-region
        kill-line-or-region-backwards
        kill-sexp
        mc/mark-all-in-region
        my-super-keyboard-quit
        org-self-insert-command
        prelude-move-beginning-of-line
        sp-backward-sexp
        sp-forward-sexp
        sp-kill-hybrid-sexp
        subword-left
        subword-right
        web-mode-attribute-insert
        x-clipboard-yank
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        crux-switch-to-previous-buffer
        helm-M-x
        helm-find-files
        kmacro-end-or-call-macro
        kmacro-start-macro-or-insert-counter
        mc/mark-next-lines
        mc/mark-previous-lines
        mouse-set-region
        repeat
        web-mode-mark-and-expand
        ))
